### ISSUE TITLE
Worked only once on Chrome for Mac

### ISSUE THREAD

**Issue by Bartman236** [pdjstone/furby-web-bluetooth#1]
Hi pdjstone,

Great project! I really like the ease of use. Tried it on Chrome for Mac and it worked like charm... only once. After that Chrome was not able to find Furby again. I tried resetting the bluetooth device via Shift+Option+Bluetooth-icon-on-top-of-the-screen -> Debug -> Reset the Bluetooth module, but no success. I also tried reinstalling Chrome, but for some reason it worked only once.
Any ideas?

**Comment by pdjstone** [comment]
Check that nothing else is connected to the Furby (e.g. a phone or tablet). Maybe also check if Mac OS has paired with the Furby - if so try unpairing it.

**Comment by Bartman236** [comment]
I checked all of that. Nothing worked. I just had the opportunity to connect to another Furby Connect. Same thing. First time works perfect. Second time the Furby cannot be found. I guess this might have to do with Chrome on Mac. Is there any way to reset or unpair the web-bluetooth settings in Chrome? Could not find how to do this on the Internet.

**Comment by pdjstone** [comment]
You could try connecting to some other Bluetooth LE device (e.g. a Fitbit) using the Web Bluetooth samples (e.g. https://googlechrome.github.io/samples/web-bluetooth/device-info.html?allDevices=true) and see if you have the same problem.

**Comment by Bartman236** [comment]
I upgraded to Mojave recently and for some reason all works now. I can connect, disconnect and reconnect without any issues.

**Comment by tetreault** [comment]
I ran into this issue also. I got the HACKED dlc loaded, activated, and functional. I then tried switching to a custom one to try out my DLC and my DLC is broken in some way because it just spits out garbled glitched out static audio. So I switch back to the HACKED dlc and can no longer get the HACKED dlc working. 

I also used the `fluffd` node script from the `bluefluff` repo to delete the DLC and tried flashing the HACKED dlc with his utility, same result :(. I don't really expect help troubleshooting that, but just wanted to pass along my results.
